controller_manager:
  ros__parameters:
    use_sim_time: true  # CRITICAL: This was missing
    update_rate: 100  # Hz
    robot_description_topic: "/robot_description"  # Add this
    
    # Hardware interface - CRITICAL: This was missing
    hardware_interface:
      - position
      - velocity

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    use_sim_time: true  # Add this
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 1.25  # Distance between wheels
    wheel_radius: 0.3       # Wheel radius
    
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    publish_rate: 50.0
    odom_frame_id: diff_drive/odom
    base_frame_id: diff_drive/chassis
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    open_loop: false
    enable_odom_tf: true
    
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    
    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0
    
    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true  # Add this
    joints:
      - left_wheel_joint
      - right_wheel_joint